export * from "./userRouter";
export * from "./gymRouter";
export * from "./badgeRouter";
export * from "./challengeRouter";
export * from "./exerciseTypeRouter";
export * from "./trainingStatRouter";
export * from "./userBadgeRouter";
export * from "./socialChallengeRouter";
export * from "./scoreRouter";