FROM node:22

WORKDIR /app

# Installation des dépendances
COPY package*.json ./
RUN npm install

# Copie du reste des fichiers
COPY . .

EXPOSE 3000

# Lancement direct du mode dev
CMD ["npm", "run", "dev"]